import { integer, primaryKey, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const people = sqliteTable('people', { id: text('id').primaryKey(), name: text('name').notNull(), color: text('color').notNull(), timezone: text('timezone').notNull().default('America/Denver') });
export const scheduleEvents = sqliteTable('schedule_events', { id: text('id').primaryKey(), personId: text('person_id').notNull().references(() => people.id), kind: text('kind', { enum: ['home', 'late_shift', 'work_trip', 'day_off', 'holiday', 'away'] }).notNull(), startsAt: integer('starts_at', { mode: 'timestamp_ms' }).notNull(), endsAt: integer('ends_at', { mode: 'timestamp_ms' }).notNull(), title: text('title').notNull(), location: text('location'), source: text('source').notNull().default('manual') });
export const ingredients = sqliteTable('ingredients', { id: text('id').primaryKey(), name: text('name').notNull().unique(), category: text('category').notNull(), baseUnit: text('base_unit').notNull(), preferredStore: text('preferred_store'), costcoEligible: integer('costco_eligible', { mode: 'boolean' }).notNull().default(false) });
export const recipes = sqliteTable('recipes', { id: text('id').primaryKey(), title: text('title').notNull(), cuisine: text('cuisine'), method: text('method'), servings: integer('servings').notNull().default(2), instructionsJson: text('instructions_json').notNull(), prepMinutes: integer('prep_minutes'), cookMinutes: integer('cook_minutes'), starred: integer('starred', { mode: 'boolean' }).notNull().default(false), rating: integer('rating'), notes: text('notes'), lastCookedAt: integer('last_cooked_at', { mode: 'timestamp_ms' }) });
export const recipeIngredients = sqliteTable('recipe_ingredients', { recipeId: text('recipe_id').notNull().references(() => recipes.id), ingredientId: text('ingredient_id').notNull().references(() => ingredients.id), quantity: real('quantity').notNull(), unit: text('unit').notNull(), preparation: text('preparation'), optional: integer('optional', { mode: 'boolean' }).notNull().default(false) }, (table) => [primaryKey({ columns: [table.recipeId, table.ingredientId] })]);
export const inventoryLots = sqliteTable('inventory_lots', { id: text('id').primaryKey(), ingredientId: text('ingredient_id').notNull().references(() => ingredients.id), estimatedQuantity: real('estimated_quantity').notNull(), unit: text('unit').notNull(), confidence: real('confidence').notNull(), purchasedAt: integer('purchased_at', { mode: 'timestamp_ms' }), expiresAt: integer('expires_at', { mode: 'timestamp_ms' }), lastConfirmedAt: integer('last_confirmed_at', { mode: 'timestamp_ms' }), source: text('source').notNull() });
export const recurringProfiles = sqliteTable('recurring_profiles', { id: text('id').primaryKey(), personId: text('person_id').notNull().references(() => people.id), name: text('name').notNull(), mealType: text('meal_type').notNull(), appliesWhen: text('applies_when').notNull(), daysOfWeekJson: text('days_of_week_json').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true) });
export const profileIngredients = sqliteTable('profile_ingredients', { profileId: text('profile_id').notNull().references(() => recurringProfiles.id), ingredientId: text('ingredient_id').notNull().references(() => ingredients.id), quantity: real('quantity').notNull(), unit: text('unit').notNull() }, (table) => [primaryKey({ columns: [table.profileId, table.ingredientId] })]);
export const mealPlanEntries = sqliteTable('meal_plan_entries', { id: text('id').primaryKey(), date: text('date').notNull(), recipeId: text('recipe_id').references(() => recipes.id), mealType: text('meal_type').notNull().default('dinner'), servings: real('servings').notNull(), status: text('status', { enum: ['planned', 'cooked', 'skipped', 'out'] }).notNull().default('planned'), rationaleJson: text('rationale_json'), completedAt: integer('completed_at', { mode: 'timestamp_ms' }) });
export const groceryRuns = sqliteTable('grocery_runs', { id: text('id').primaryKey(), store: text('store').notNull(), windowStart: text('window_start').notNull(), windowEnd: text('window_end').notNull(), cadence: text('cadence').notNull(), status: text('status', { enum: ['draft', 'ready', 'shopping', 'complete'] }).notNull().default('draft') });
export const groceryItems = sqliteTable('grocery_items', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => groceryRuns.id), ingredientId: text('ingredient_id').notNull().references(() => ingredients.id), requiredQuantity: real('required_quantity').notNull(), unit: text('unit').notNull(), purchasedQuantity: real('purchased_quantity'), checked: integer('checked', { mode: 'boolean' }).notNull().default(false), reasonJson: text('reason_json').notNull() });
export const inventoryTransactions = sqliteTable('inventory_transactions', { id: text('id').primaryKey(), ingredientId: text('ingredient_id').notNull().references(() => ingredients.id), kind: text('kind', { enum: ['purchase', 'planned_consumption', 'confirmed_consumption', 'adjustment', 'waste'] }).notNull(), quantity: real('quantity').notNull(), unit: text('unit').notNull(), confidenceDelta: real('confidence_delta').notNull().default(0), relatedId: text('related_id'), occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull() });
